/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ActivityApi,
  FilesApi,
  HealthApi,
  ItemsApi,
  MetricsApi,
  VaultsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { OnePasswordConnectCustom } from "./client-custom";

export class OnePasswordConnect extends OnePasswordConnectCustom {
  readonly activity: ActivityApi;
  readonly files: FilesApi;
  readonly health: HealthApi;
  readonly items: ItemsApi;
  readonly metrics: MetricsApi;
  readonly vaults: VaultsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.activity = new ActivityApi(configuration);
    this.files = new FilesApi(configuration);
    this.health = new HealthApi(configuration);
    this.items = new ItemsApi(configuration);
    this.metrics = new MetricsApi(configuration);
    this.vaults = new VaultsApi(configuration);
  }

}
