/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { APIRequestResourceVault } from './apirequest-resource-vault';

/**
 * 
 * @export
 * @interface APIRequestResource
 */
export interface APIRequestResource {
    /**
     * 
     * @type {string}
     * @memberof APIRequestResource
     */
    'type'?: APIRequestResourceTypeEnum;
    /**
     * 
     * @type {APIRequestResourceVault}
     * @memberof APIRequestResource
     */
    'vault'?: APIRequestResourceVault;
    /**
     * 
     * @type {APIRequestResourceVault}
     * @memberof APIRequestResource
     */
    'item'?: APIRequestResourceVault;
    /**
     * 
     * @type {number}
     * @memberof APIRequestResource
     */
    'itemVersion'?: number;
}

type APIRequestResourceTypeEnum = 'ITEM' | 'VAULT'


