/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { APIRequestActor } from './apirequest-actor';
import { APIRequestResource } from './apirequest-resource';

/**
 * Represents a request that was made to the API. Including what Token was used and what resource was accessed.
 * @export
 * @interface APIRequest
 */
export interface APIRequest {
    /**
     * The unique id used to identify a single request.
     * @type {string}
     * @memberof APIRequest
     */
    'requestId'?: string;
    /**
     * The time at which the request was processed by the server.
     * @type {string}
     * @memberof APIRequest
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIRequest
     */
    'action'?: APIRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof APIRequest
     */
    'result'?: APIRequestResultEnum;
    /**
     * 
     * @type {APIRequestActor}
     * @memberof APIRequest
     */
    'actor'?: APIRequestActor;
    /**
     * 
     * @type {APIRequestResource}
     * @memberof APIRequest
     */
    'resource'?: APIRequestResource;
}

type APIRequestActionEnum = 'READ' | 'CREATE' | 'UPDATE' | 'DELETE'
type APIRequestResultEnum = 'SUCCESS' | 'DENY'


