/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface APIRequestActor
 */
export interface APIRequestActor {
    /**
     * 
     * @type {string}
     * @memberof APIRequestActor
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIRequestActor
     */
    'account'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIRequestActor
     */
    'jti'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIRequestActor
     */
    'userAgent'?: string;
    /**
     * 
     * @type {string}
     * @memberof APIRequestActor
     */
    'requestIp'?: string;
}

