/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * HTTP Status Code
     * @type {number}
     * @memberof ErrorResponse
     */
    'status'?: number;
    /**
     * A message detailing the error
     * @type {string}
     * @memberof ErrorResponse
     */
    'message'?: string;
}

