/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldSection } from './field-section';
import { GeneratorRecipe } from './generator-recipe';

/**
 * 
 * @export
 * @interface Field
 */
export interface Field {
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    'id': string;
    /**
     * 
     * @type {FieldSection}
     * @memberof Field
     */
    'section'?: FieldSection;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    'type': FieldTypeEnum;
    /**
     * Some item types, Login and Password, have fields used for autofill. This property indicates that purpose and is required for some item types.
     * @type {string}
     * @memberof Field
     */
    'purpose'?: FieldPurposeEnum;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    'value'?: string;
    /**
     * If value is not present then a new value should be generated for this field
     * @type {boolean}
     * @memberof Field
     */
    'generate'?: boolean;
    /**
     * 
     * @type {GeneratorRecipe}
     * @memberof Field
     */
    'recipe'?: GeneratorRecipe;
    /**
     * For fields with a purpose of `PASSWORD` this is the entropy of the value
     * @type {number}
     * @memberof Field
     */
    'entropy'?: number;
}

type FieldTypeEnum = 'STRING' | 'EMAIL' | 'CONCEALED' | 'URL' | 'TOTP' | 'DATE' | 'MONTH_YEAR' | 'MENU'
type FieldPurposeEnum = '' | 'USERNAME' | 'PASSWORD' | 'NOTES'


