/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * For files that are in a section, this field describes the section.
 * @export
 * @interface FileSection
 */
export interface FileSection {
    /**
     * 
     * @type {string}
     * @memberof FileSection
     */
    'id'?: string;
}

