/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Field } from './field';
import { FullItemAllOfSections } from './full-item-all-of-sections';

/**
 * 
 * @export
 * @interface FullItemAllOf
 */
export interface FullItemAllOf {
    /**
     * 
     * @type {Array<FullItemAllOfSections>}
     * @memberof FullItemAllOf
     */
    'sections'?: Array<FullItemAllOfSections>;
    /**
     * 
     * @type {Array<Field>}
     * @memberof FullItemAllOf
     */
    'fields'?: Array<Field>;
    /**
     * 
     * @type {Array<any>}
     * @memberof FullItemAllOf
     */
    'files'?: Array<any>;
}

