/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Field } from './field';
import { FullItemAllOf } from './full-item-all-of';
import { FullItemAllOfSections } from './full-item-all-of-sections';
import { Item } from './item';
import { ItemUrlsInner } from './item-urls-inner';
import { ItemVault } from './item-vault';

/**
 * @type FullItem
 * @export
 */
export type FullItem = FullItemAllOf & Item;


