/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceDependency } from './service-dependency';

/**
 * 
 * @export
 * @interface HealthServerStateCheckResponse
 */
export interface HealthServerStateCheckResponse {
    /**
     * The Connect server\'s version
     * @type {string}
     * @memberof HealthServerStateCheckResponse
     */
    'version': string;
    /**
     * 
     * @type {string}
     * @memberof HealthServerStateCheckResponse
     */
    'name': string;
    /**
     * 
     * @type {Array<ServiceDependency>}
     * @memberof HealthServerStateCheckResponse
     */
    'dependencies'?: Array<ServiceDependency>;
}

