/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ItemUrlsInner } from './item-urls-inner';
import { ItemVault } from './item-vault';

/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {Array<string>}
     * @memberof Item
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'title'?: string;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    'version'?: number;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'id'?: string;
    /**
     * 
     * @type {ItemVault}
     * @memberof Item
     */
    'vault': ItemVault;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'category': ItemCategoryEnum;
    /**
     * 
     * @type {Array<ItemUrlsInner>}
     * @memberof Item
     */
    'urls'?: Array<ItemUrlsInner>;
    /**
     * 
     * @type {boolean}
     * @memberof Item
     */
    'favorite'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'state'?: ItemStateEnum;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    'lastEditedBy'?: string;
}

type ItemCategoryEnum = 'LOGIN' | 'PASSWORD' | 'API_CREDENTIAL' | 'SERVER' | 'DATABASE' | 'CREDIT_CARD' | 'MEMBERSHIP' | 'PASSPORT' | 'SOFTWARE_LICENSE' | 'OUTDOOR_LICENSE' | 'SECURE_NOTE' | 'WIRELESS_ROUTER' | 'BANK_ACCOUNT' | 'DRIVER_LICENSE' | 'IDENTITY' | 'REWARD_PROGRAM' | 'DOCUMENT' | 'EMAIL_ACCOUNT' | 'SOCIAL_SECURITY_NUMBER' | 'MEDICAL_RECORD' | 'SSH_KEY' | 'CUSTOM'
type ItemStateEnum = 'ARCHIVED' | 'DELETED'


