/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ItemUrlsInner
 */
export interface ItemUrlsInner {
    /**
     * 
     * @type {string}
     * @memberof ItemUrlsInner
     */
    'label'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ItemUrlsInner
     */
    'primary'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ItemUrlsInner
     */
    'href': string;
}

