/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FileSection } from './file-section';

/**
 * 
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
    /**
     * ID of the file
     * @type {string}
     * @memberof ModelFile
     */
    'id'?: string;
    /**
     * Name of the file
     * @type {string}
     * @memberof ModelFile
     */
    'name'?: string;
    /**
     * Size in bytes of the file
     * @type {number}
     * @memberof ModelFile
     */
    'size'?: number;
    /**
     * Path of the Connect API that can be used to download the contents of this file.
     * @type {string}
     * @memberof ModelFile
     */
    'content_path'?: string;
    /**
     * 
     * @type {FileSection}
     * @memberof ModelFile
     */
    'section'?: FileSection;
    /**
     * Base64-encoded contents of the file. Only set if size <= OP_MAX_INLINE_FILE_SIZE_KB kb and `inline_files` is set to `true`.
     * @type {string}
     * @memberof ModelFile
     */
    'content'?: string;
}

