/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The state of a registered server dependency.
 * @export
 * @interface ServiceDependency
 */
export interface ServiceDependency {
    /**
     * 
     * @type {string}
     * @memberof ServiceDependency
     */
    'service'?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDependency
     */
    'status'?: string;
    /**
     * Human-readable message for explaining the current state.
     * @type {string}
     * @memberof ServiceDependency
     */
    'message'?: string;
}

