/*
1Password Connect

REST API interface for 1Password Connect.

The version of the OpenAPI document: 1.5.7
Contact: support@1password.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Vault
 */
export interface Vault {
    /**
     * 
     * @type {string}
     * @memberof Vault
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Vault
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Vault
     */
    'name'?: string;
    /**
     * The vault version
     * @type {number}
     * @memberof Vault
     */
    'attributeVersion'?: number;
    /**
     * The version of the vault contents
     * @type {number}
     * @memberof Vault
     */
    'contentVersion'?: number;
    /**
     * Number of active items in the vault
     * @type {number}
     * @memberof Vault
     */
    'items'?: number;
    /**
     * 
     * @type {string}
     * @memberof Vault
     */
    'type'?: VaultTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Vault
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Vault
     */
    'updatedAt'?: string;
}

type VaultTypeEnum = 'USER_CREATED' | 'PERSONAL' | 'EVERYONE' | 'TRANSFER'


